# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5498f61fec85690a579550dda7cf9b315536b51e0796e98f608903c36444a80425b227270e4f90016c3856475ae8322f844dc9367a43379aaf37b6392077f34

test:
  secret_key_base: 86d4cb6d1a672c9f9fa88f60d6b824f4c9f0207120cc7db4a75341735a83d690c1d9a06c3e20220c55fedaded36993844e577d93c42947310b2e9d3ddd3e3b76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
